#!/bin/bash
# Disk Space Alert - Generated by Mistral
# Simple, fast monitoring for FBCA systems

THRESHOLD=90
USAGE=$(df / | tail -1 | awk '{print $5}' | tr -d '%')

alert() {
    MSG="🚨 Disk Alert: ${USAGE}% used on $(hostname -s)"
    echo "$MSG"
    
    # Try Telegram first
    if [[ -n "${TELEGRAM_BOT_TOKEN:-}" ]]; then
        curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID:-}" \
            -d "text=${MSG}" 2>/dev/null
    fi
}

if (( USAGE > THRESHOLD )); then
    alert
    logger -t disk_monitor "CRITICAL: ${USAGE}% disk usage"
    exit 1
fi

echo "Disk OK: ${USAGE}%"
exit 0